### PR TITLE
Fix encrypted files not downloading properly due to incorrect Content-Length header value

### LINKED ISSUE #20: Encrypted files don't download properly due to incorrect Content-Length header value
I have successfully implemented file encryption (using `real_aes`) and have it working with most cases I have tested, but I cannot get it to work with PDF files. It saves and appears to encrypt the files, but when I attempt to download them the request always whitescreens. It doesn't cause any PHP errors or warnings, and it doesn't save any messages in the log. Following the request logic with Xdebug, I see that it gets all the way to sending a `BinaryFileResponse` with a `file` member that looks correct and terminating the kernel cycle. Firefox Developer Tools indicate that the browser is receiving an HTTP 200 response of HTML type a little smaller than the actual file (289K, whereas the original PDF is 292K).

I'm really not sure where to go from here. Has `file_encrypt` been tested with PDF files, specifically? Does anyone have any recommendations how I might proceed from here to isolate the problem? cc @dawehner

### PR DESCRIPTION
**Pull request by TravisCarden**
Fixes #20.

### CODE REVIEW

**Comment by nerdstein** [comment]
Reviewing the code

**Comment by nerdstein** [comment]
Code has been merged, still waiting on TravisCI to finish it's business

File: src/Controller/ImageStyleDownloadController.php [hunk 1]
```diff
@@ -6,7 +6,6 @@
 use Drupal\Core\Image\ImageFactory;
 use Drupal\Core\Lock\LockBackendInterface;
 use Drupal\image\ImageStyleInterface;
-use Drupal\system\FileDownloadController;
```
Comment (TravisCarden) [inline src/Controller/ImageStyleDownloadController.php:9]: This removal causes the image style download controller to inherit from our new (fixed) file download controller rather than core's. Note that I'm not using image styles and haven't tested them--before or after this change.

**Comment by nerdstein** [comment]
TravisCI seems to be unhappy and getting hung up on downloading Encrypt
